export const DERIVATION_REQUEST = 'DERIVATION_REQUEST'
export const DERIVATION_SUCCES = 'DERIVATION_SUCCES'
export const DERIVATION_CANCEL = 'DERIVATION_CANCEL'
export const DERIVATION_FAIL = 'DERIVATION_FAIL'