export const DERIVATION_REQUEST = 'DERIVATION_REQUEST';
export const DERIVATION_SUCCESS = 'DERIVATION_SUCCESS';
export const DERIVATION_CANCEL = 'DERIVATION_CANCEL';
export const DERIVATION_FAIL = 'DERIVATION_FAIL';