export const COMPARISON_REQUEST = 'COMPARISON_REQUEST';
export const COMPARISON_SUCCESS = 'COMPARISON_SUCCESS';
export const COMPARISON_CANCEL = 'COMPARISON_CANCEL';
export const COMPARISON_FAIL = 'COMPARISON_FAIL';
