export const CFGUNITREMOVAL_REQUEST = 'CFGUNITREMOVAL_REQUEST';
export const CFGUNITREMOVAL_SUCCESS = 'CFGUNITREMOVAL_SUCCESS';
export const CFGUNITREMOVAL_CANCEL = 'CFGUNITREMOVAL_CANCEL';
export const CFGUNITREMOVAL_FAIL = 'CFGUNITREMOVAL_FAIL';