version: '3.2'

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      cache_from:
      - node:8.12-alpine
    image: frontend:latest
    ports:
    - "3000:3000"
    volumes:
    - ./frontend/src:/home/node/src:ro

  backend:
    restart: always
    image: backend:latest
    environment:
    - FLASK_ENV=development
    ports:
    - "5000:5000"
    volumes:
    - ./Backend/backend:/srv/Backend/backend:ro
    depends_on:
    - backend_tests
    command: ["--host=0.0.0.0"]

  backend_tests:
    restart: "no"
    build:
      context: ./Backend
      cache_from:
      - python:3.6.5-alpine
      - gitlab.fit.cvut.cz:5000/algorithms-library-toolkit/automata-library:v0.0.1
    image: backend:latest
    environment:
    - FLASK_ENV=testing
    volumes:
    - ./Backend/backend:/srv/Backend/backend:ro
    - ./Backend/tests:/srv/Backend/tests:ro
    entrypoint:
    - pytest
    command:
    - tests/interface_test.py::test_algorithm_result
