export const EPSREMOVAL_REQUEST = 'EPSREMOVAL_REQUEST'
export const EPSREMOVAL_SUCCESS = 'EPSREMOVAL_SUCCESS'
export const EPSREMOVAL_CANCEL = 'EPSREMOVAL_CANCEL'
export const EPSREMOVAL_FAIL = 'EPSREMOVAL_FAIL'