export const LEFTRECREMOVAL_REQUEST = 'LEFTRECREMOVAL_REQUEST';
export const LEFTRECREMOVAL_SUCCESS = 'LEFTRECREMOVAL_SUCCESS';
export const LEFTRECREMOVAL_CANCEL = 'LEFTRECREMOVAL_CANCEL';
export const LEFTRECREMOVAL_FAIL = 'LEFTRECREMOVAL_FAIL';