export const DETERMINIZATION_REQUEST = 'DETERMINIZATION_REQUEST';
export const DETERMINIZATION_SUCCES = 'DETERMINIZATION_SUCCES';
export const DETERMINIZATION_CANCEL = 'DETERMINIZATION_CANCEL';
export const DETERMINIZATION_FAIL = 'DETERMINIZATION_FAIL';