export const CFGEPSREMOVAL_REQUEST = 'CFGEPSREMOVAL_REQUEST';
export const CFGEPSREMOVAL_SUCCESS = 'CFGEPSREMOVAL_SUCCESS';
export const CFGEPSREMOVAL_CANCEL = 'CFGEPSREMOVAL_CANCEL';
export const CFGEPSREMOVAL_FAIL = 'CFGEPSREMOVAL_FAIL';