export const CFGREDUCTION_REQUEST = 'CFGREDUCTION_REQUEST';
export const CFGREDUCTION_SUCCESS = 'CFGREDUCTION_SUCCESS';
export const CFGREDUCTION_CANCEL = 'CFGREDUCTION_CANCEL';
export const CFGREDUCTION_FAIL = 'CFGREDUCTION_FAIL';