export const MINIMIZATION_REQUEST = 'MINIMIZATION_REQUEST'
export const MINIMIZATION_SUCCESS = 'MINIMIZATION_SUCCESS'
export const MINIMIZATION_CANCEL = 'MINIMIZATION_CANCEL'
export const MINIMIZATION_FAIL = 'MINIMIZATION_FAIL'