export const TRANSFORMATION_REQUEST = 'TRANSFORMATION_REQUEST';
export const TRANSFORMATION_SUCCESS = 'TRANSFORMATION_SUCCESS';
export const TRANSFORMATION_CANCEL = 'TRANSFORMATION_CANCEL';
export const TRANSFORMATION_FAIL = 'TRANSFORMATION_FAIL';